import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashCursor from "@/components/SplashCursor/SplashCursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='from-gray-900 via-slate-800 to-gray-900 '>
        <SplashCursor />
        {children}
      </body>
    </html>
  );
}